- name: TEMP2 
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print
      debug:
         msg: "LER-SAK PHONANG"

    - name: Collection instance info
      os_server_info:
        cloud: "devstack"
      register: instances
