- name: TEMP2 
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print
      debug:
         msg: "LER-SAK PHONANG"

    - name: Collection instance info
      os_server_info:
        #cloud: "5f64-project"
        #region_name: "{{ openstack_region | default('regionOne') }}"
      register: instances


    - name: Listing Group
      debug: var=instances
